export const GAME_CONSTANTS = {
  // Character
  CHARACTER_SPEED_BASE: 5,
  CHARACTER_HEIGHT: 1.5,
  CHARACTER_RADIUS: 0.5,

  // Path
  SEGMENT_LENGTH: 20,
  SEGMENT_WIDTH: 4,
  SPAWN_DISTANCE: 100,
  DESPAWN_DISTANCE: 20,
  PATH_HEIGHT: 0.5,

  // Gap
  GAP_WIDTH: 2,
  GAP_SAFE_DISTANCE: 2,

  // Game Loop
  FIXED_TIMESTEP: 1000 / 60,

  // Camera
  CAMERA_FOV: 45,
  CAMERA_DISTANCE: 25,
  CAMERA_OFFSET_Y: 12,
  CAMERA_OFFSET_Z: -15,
  CAMERA_FOLLOW_SMOOTHNESS: 0.1,

  // HUD
  TILE_COUNT: 6,
  TILE_SPACING: 1.8,
  TILE_Y_POSITION: -4,
  EQUATION_Y_POSITION: 4,

  // Animation
  TILE_FLY_DURATION: 500,
  TILE_SELECTION_SCALE_DURATION: 200,
  FALLING_DURATION: 1000,
};
